### ISSUE TITLE
Second Scala cell is forced as Markdown

### ISSUE THREAD

**Issue by rockt** [wolfe-pack/moro#63] opened 2015-05-17 13:21 UTC
If I start with a Scala cell and add another one after that, the second cell will be a markdown cell and I cannot change the type of it to Scala without reloading the editor.

**Comment by sameersingh** [comment] 2015-05-17 23:41
Can you describe the exact steps, starting from a brand new notebook?
Especially how you are adding new cells, etc. I need to reproduce it at my
end.

**Comment by sameersingh** [comment] 2015-06-30 07:37
I think I fixed this, possibly duplicate of #71.

**Closed by sameersingh** 2015-06-30 07:37 UTC
